image: nikolaik/python-nodejs:python3.10-nodejs18

include:
  - project: geoplateforme/templates
    ref: main
    file:
      - "ci/docker-v5.yml"
      - "ci/chart-v2.yml"
      - "ci/versioning.yml"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

cache:
  paths:
    - node_modules/

lint:
  script:
    - yarn --frozen-lockfile
    - yarn lint

test:
  before_script:
    - apt-get update && apt-get install -y p7zip-full
  script:
    - yarn --frozen-lockfile
    - yarn test-lcov
  artifacts:
    paths:
      - coverage/lcov.info
    expire_in: 1 week

test:recette:
  script:
    - yarn --frozen-lockfile
    - yarn test-recette
  when: manual
