services:
  api:
    build: .
    command: yarn api:start
    ports:
      - "3000:3000"
    environment:
      ADDRESS_INDEX_URL: http://address:3000
      PARCEL_INDEX_URL: http://parcel:3000
      POI_INDEX_URL: http://poi:3000
  address:
    build: .
    command: bash -c "yarn address:download-index && yarn address:start"
    environment:
      ADDRESS_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-address-latest
  parcel:
    build: .
    command: bash -c "yarn parcel:download-index && yarn parcel:start"
    environment:
      PARCEL_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-parcel-latest
  poi:
    build: .
    command: bash -c "yarn poi:download-index && yarn poi:start"
    environment:
      POI_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-poi-latest
